# Generated by Django 5.2.4 on 2025-09-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('api_url', models.URLField()),
                ('documentation_url', models.URLField()),
                ('auth_required', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('additional_info', models.TextField()),
            ],
        ),
    ]
